[package]
name = "insert-json"
version = "0.1.0"
edition = "2021"

[dependencies]
ewebsock = { version = "0.6.0", features = ["tls"] }
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
packet = { path="../../packet"}
rand = "0.8.5"